### ISSUE TITLE
Additional log levels

### ISSUE THREAD

**Issue by dpo** [colinfang/MiniLogging.jl#1]
Thanks for logging done right!

Is there a way to add additional logging levels (e.g., TRACE)? If not, would it make sense to add a new level in the package or to come up with a way for users to add levels?

**Comment by colinfang** [comment]
I added the feature just now.
Could you try `Pkg.clone("https://github.com/colinfang/MiniLogging.jl")` and follow the "Add A New Level" section in the README to see if it works for you?

**Comment by dpo** [comment]
Thanks for the fast response! I'm not a macro expert but I think something related to hygiene may be going on:
```julia
julia> using MiniLogging

julia> basic_config(MiniLogging.DEBUG; date_format="%Y-%m-%d %H:%M:%S")
1-element Array{MiniLogging.Handler,1}:
 MiniLogging.Handler(Base.TTY(open, 0 bytes waiting),"%Y-%m-%d %H:%M:%S")

julia> MiniLogging.define_new_level(:trace, 5, :yellow)

julia> logger = get_logger("bla")
Logger("bla", NOTSET:0)

julia> logger.level = MiniLogging.trace
ERROR: MethodError: Cannot `convert` an object of type Base.LinAlg.#trace to an object of type Int64
This may have arisen from a call to the constructor Int64(...),
since type constructors fall back to convert methods.
```

For the existing levels, the macro is lowercase but the level itself is uppercase, which is not the case with the new level. I suppose that's a small adjustment.

If I try `:TRACE` instead of `:trace`,
```julia
julia> MiniLogging.define_new_level(:TRACE, 5, :yellow)

julia> logger.level = MiniLogging.TRACE
ERROR: UndefVarError: TRACE not defined
```
However
```julia
julia> MiniLogging.DEFINED_LEVELS
Dict{Int64,Symbol} with 7 entries:
  0  => :NOTSET
  30 => :WARN
  10 => :DEBUG
  50 => :CRITICAL
  40 => :ERROR
  5  => :TRACE
  20 => :INFO
```
Of course I can do
```julia
julia> logger.level = 5;

julia> @TRACE(logger, "boo!")
2017-05-04 16:34:11:TRACE:bla:boo!
```

**Comment by colinfang** [comment]
The way I expected that the customized level would be used is like that:

```julia
const TRACE = 5
MiniLogging.define_new_level(:trace, TRACE, :yellow)
logger.level = TRACE
@trace(logger, "boo!")
```

That is, `define_new_level` only defines and exposes a macro for you, i.e. `@trace` in this case. It doesn't define a level constant. Because you can easily do it yourself outside the module, i.e. `const TRACE= 5`

**Comment by dpo** [comment]
I see. It makes sense. Thanks for implementing this so fast!
